### ISSUE TITLE
2.2.1 broke our tests

### ISSUE THREAD

**Issue by JTLunsford** [websockets/ws#1043]
server.close(() => {
   expect(client.readyState()).to.be.equal(3)
})

Error:
Uncaught AssertionError: expected 1 to equal 3
+ expected - actual

-1
+3

**Comment by JTLunsford** [comment]
moved back to 2.2.0 fixed our issue

**Comment by lpinca** [comment]
`WebSocket.prototype.terminate()` now destroys the underlying socket instead of sending a FIN packet so the callback of `WebSocketServer.prototype.close()` is called earlier than before.

When the callback is invoked the client `readyState` is still `WebSocket.OPEN` (1) but if you add a small delay it should correctly be updated to `WebSocket.CLOSED` (3).
