### ISSUE TITLE
How to make the binary data as ArrayBuffer , not node-Buffer ? 

### ISSUE THREAD

**Issue by finscn** [websockets/ws#1045]
How to make the binary data as ArrayBuffer directly , not convert from Buffer ? 

When set  binaryType === 'arraybuffer' , the ws will call : 
```
  data = new Uint8Array(data).buffer;
```
The performance of this operation  is bad.

**Comment by JacksonTian** [comment]
What's your Node version?

**Comment by lpinca** [comment]
Node.js gives us `Buffer` instances so we have to convert them to `ArrayBuffer` when the user sets `binaryType` to `arraybuffer`.

This is how we do it: https://github.com/websockets/ws/blob/1b3810ed95d2d2572314b3c361e97eaab73c41ef/lib/Receiver.js#L545-L551.

The same also happens when sending an `ArrayBuffer` but in [this case](https://github.com/websockets/ws/blob/1b3810ed95d2d2572314b3c361e97eaab73c41ef/lib/Sender.js#L259) conversion is a lot faster.

**Comment by finscn** [comment]
@JacksonTian  Node 6.9.5

@lpinca , I see , thanks.
