### ISSUE TITLE
ws.send(message) will lost message if a client disconnects due to network failure.

### ISSUE THREAD

**Issue by ghost** [websockets/ws#1103]
use `ws.send(message)` to send message to client  ,if a client disconnects  due to network failure, the message will lost .can we change the method ,make `ws.send(message, timeout, function(err, ack, timeout) {};`  if server  could not  get the response of ack from  client,we can know the connect is failure and  do somtthing to save msg?

like  this

```js
ws.send('msg', 'timeout', function (err, ack, timeout) {
  // the connnect is opend and readystate is one 
  // no err but if in the set timeout, the return will set error
  if (timeout) { 
    doSomething();
  } 
});
```

**Comment by lpinca** [comment]
I don't think this will help. The callback of `ws.send()` is forwarded to [`socket.write()`](https://nodejs.org/dist/latest/docs/api/net.html#net_socket_write_data_encoding_callback).

Consider this example:

```js

function send(ws, msg, timeout) {
  let timer;

  ws.send(msg, function (err) {
    clearTimeout(timer);
    if (err) handleError();
  });

  timer = setTimeout(function () {
    // What to do here?
  }, timeout);
}
```

When the timeout expires the data is still not written out but it may be in a later moment. There is no way for us to know. We can only rely on the callback.

**Comment by binginto** [comment]
Maybe I didn't make it clear, thanks for your answer.

Now  the question is  server  cant  know  if a client disconnects due to network failure. even if  you use the  ping-pong or hearttime to close the dead connect. but  there will  still lost message if ws.send(message) between  network failure and closed client . 

I know  when  ws.send(message) ,if the network is good ,the client will send an  ack response to server on TCP protocol layer. we can set a timer,if server cant receive the ack response on time.it means the connnect is error.And  make the  callback of ws.send will carry out  when the server cant receive the ack response  but not just  send message to TCP send buffer. because  server can receive the ack response from client in TCP protocol means the connnetc is good ,but just not just  send message to TCP send buffer cant  do it .

user your code 

function send(ws, msg, timeout) {
  let timer;

  ws.send(msg, function (err) {
//callback will  do until  receive the ack response
//but not  just  send message to TCP send buffer
//however I dont know how to change it 
    clearTimeout(timer);
    if (err) handleError();
  });

  timer = setTimeout(function () {
    // What to do here?
  }, timeout);
}

**Comment by lpinca** [comment]
Yes, my point is that we have no control on the callback as it is handled by Node.js core.

**Comment by lpinca** [comment]
Closing this as I think there isn't anything actionable for us to do.
