### ISSUE TITLE
Websocket.Server is not able to co-exists with anther websocket server.

### ISSUE THREAD

**Issue by DxCx** [websockets/ws#1193]
#### Description

Hey,
On websocket server, if a `path` is given and the connection does not handle it,
it will call abortConnection:
https://github.com/websockets/ws/blob/6663b89cd7c19269c6f9a527e96f3cd7db0c5fea/lib/WebSocketServer.js#L155-L161

now, assuming i'm running 2 websocket implementations over the same socket,
it will just terminate the socket that should be handled by the other server.

I'm not sure how you want to tackle this, but IMO the solution shall be as simple as adding a flag indicating to not close unaccepted connections.
(I've already confirmed that sock-js keep working if ws.Server won't destroy the connection)

Related to https://github.com/apollographql/subscriptions-transport-ws/issues/235
which is running sock-js implementation along with ws.Server

#### Reproducible in:

version:
Node.js version(s): 8.3.0
OS version(s): macOS 10.12.6

#### Steps to reproduce:

1. Open Sock-js server
2. bind Ws.Server to the same http Server. (With diffrent `path`)
3. sock-js endpoint is broken.

### Expected result:

Both paths (/sock-js + `path` of ws.Server) should work normally.

### Actual result:

ws.Server will terminate sock-js handshake instead of ignore it.

**Comment by lpinca** [comment]
See https://github.com/websockets/ws/pull/885.

**Comment by DxCx** [comment]
Thanks @Ipinca that's a solution as well, and it works 👍

**Comment by jedwards1211** [comment]
@lpinca there's not really a way to use that workaround with `ApolloServer.installSubscriptionHandlers`; I have to copy a bunch of code out of `installSubscriptionHandlers` to be able to use that workaround.

I wish I could just tell `WebSocket.Server` to ignore requests to other paths instead of aborting the handshake.  Can we add an option to `WebSocket.Server` that tells it to ignore other paths?
