### ISSUE TITLE
FAQ Example Ping Pong not working

### ISSUE THREAD

**Issue by opit7** [websockets/ws#1452]
#### Description
Hello I am having problems with the example to detect if a websocket disconnects. I am using the example provided in the FAQ.

#### Steps to reproduce:
1. use faq example  
```javascript
const interval = setInterval(function ping() {
  console.log("intervalOuter");
  console.log(wss.clients);
  wss.clients.forEach(function each(ws) {
    console.log("intervalInner");
    if (ws.isAlive === false) return ws.terminate();
    ws.isAlive = false;
    ws.ping(noop);
  });
}, 30000);
```
2. disconnect client

### Expected result:
`if (ws.isAlive === false) return ws.terminate();` will be executed

### Actual result:
`wss.clients` set is empty --> `if (ws.isAlive === false) return ws.terminate();` is never reached --> log.txt

### Attachments:
[log.txt](https://github.com/websockets/ws/files/2430731/log.txt)

**Comment by lpinca** [comment]
> Sometimes the link between the server and the client can be interrupted in a way that keeps both the server and the client unaware of the broken state of the connection (e.g. when pulling the cord).

I think you didn't understand, the example shows how to detect and close zombie connections. Connections that seems established but are broken in reality. This does not happen under normal circumstances and when the `'close'` event is emitted the corresponding WebSocket is removed from the `clients` set.

You find the set empty because the connection is removed from the `clients` set before the interval timeout expires.

Hope this makes sense.

**Comment by opit7** [comment]
Yes it does. Thank you for your reply.
