### ISSUE TITLE
The client cannot receive ping or pong from the server?

### ISSUE THREAD

**Issue by yqsailor** [websockets/ws#1508]
When the the server send ping or pong by ws.ping and ws.pong() , but the client cannot receive it, what should I do?

**Comment by lpinca** [comment]
We a ping is received, the other peer automatically answer with a pong. This is per specification.
In the browser there is no way to see when a ping is received, but if it is a pong is sent in response because the implementation is spec compliant.

You can verify this by listening to `'pong'` events on the server.

**Comment by yqsailor** [comment]
Oh, I see, thanks very much!

**Comment by gitcatrat** [comment]
@lpinca Sorry for reviving this issue but 1 similar question: 

If client wants to know if connection is intact (e.g reconnect), it has to send its own pings? This seems super wasteful. I'm not able to catch server pings on client and no messages appear in Chrome dev messages tab, unless `send` is used.

If that's the case, it might be actually cheaper to manually send ping messages that client can read as well:
```js
ws.send(JSON.stringify({type: 'ping'}));
```

**Comment by netizen-ais** [comment]
@gitcatrat You can see the pings on the Firefox developer tools
