### ISSUE TITLE
Docs don't say that the constructor doesn't callback if server is provided 

### ISSUE THREAD

**Issue by bentorkington** [websockets/ws#1554]
- [Y] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

When I searched for related issues, I found this was tackled years ago in #179. However the documentation has since been updated, and again it doesn't mention the fact that the constructor will not call `callback` if an HTTP server is provided.

As someone mentioned  in #179, it doesn't really make sense to use the callback if you're providing your own HTTP server anyway, and I agree with this, but I still think the documentation should mention it.

#### Reproducible in:

- version: HEAD

**Comment by lpinca** [comment]
I think the docs is clear:

> `callback` will be added as a listener for the `'listening'` event on the HTTP server when not operating in "noServer" mode.

The listener is added when a server is provided and will be called if the `'listening'` even has not already been emitted.

If you call `server.listen()` and then pass the instance to the WebSocket server constructor after the server is listening, then of course the callback is not called because the listener is added after the `'listening'` event is emitted.

If you think this can be improved/clarified further please open a PR.
