### ISSUE TITLE
readme ping/pong should indicate that the 'client' part of excludes browsers

### ISSUE THREAD

**Issue by Spongman** [websockets/ws#1569]
i wasted a bunch of time trying to get the 2nd part of the ping/pong example in the README to work in the browser. it's not obvious that 'client' really means 'another node client, not the browser'. given that probably many people will be using the browser as the client, it should probably point out that the 2nd part isn't going to work for them.

**Comment by 3rd-Eden** [comment]
That sounds like a great first contribution :D

**Comment by lpinca** [comment]
It is not explicitly specified that the example is for Node.js but it can be deduced from

1. The use of `require('ws')` instead of `Window.WebSocket`.
1. The use of `WebSocket.prototype.on()`. There is no equivalent in the browser.
1. The use of the `'ping'` event. This event does not exist in the browser. Also browsers do not allow the user to send ping/pong frames.

**Comment by Spongman** [comment]
Anyone who knows all this is probably not reading there readme.

**Comment by lpinca** [comment]
The documentation is useful for anyone that does not know how to use this module regardless of their knowledge of the WebSocket protocol or its implementations.

All documentation in this repository is for this module and nothing else. Other implementations have their own documentation. Anyone reading the README or https://github.com/websockets/ws/blob/master/doc/ws.md reads the documentation of `ws` not the browser WebSocket.

That said a PR to clarify that the example is for `ws` is welcome.

**Comment by Spongman** [comment]
ok. i'm just going to close this. apologies to those that will also be confused by this.
