### ISSUE TITLE
Type error on error closing connection 

### ISSUE THREAD

**Issue by grimkirill** [websockets/ws#1591]
- [x] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

Type error:

node_modules/ws/lib/websocket.js:900
  websocket.readyState = WebSocket.CLOSING;
                       ^

TypeError: Cannot set property 'readyState' of undefined

#### Reproducible in:

- version: ^7.0.0
- Node.js version(s): 8
- OS version(s): ubuntu 18

#### Steps to reproduce:

1. Connect

2. Disconnect by broken connection 

3.

**Comment by lpinca** [comment]
Are you able to create a reproducible test case? This can only happen if the `'error'` event is emitted after the `'close'` event on the `net.Socket` but it would be a bug in Node.js.

**Comment by grimkirill** [comment]
It was easy reproduced on production load.
v6.1.4  has additional check, that allow pass this error
```
if (websocket) {
    websocket.readyState = WebSocket.CLOSING;
    this.destroy();
  }
```

**Comment by lpinca** [comment]
Yes, it was originally needed due to this issue: https://github.com/websockets/ws/issues/1226.

We fixed it in

- https://github.com/websockets/ws/pull/1464
- https://github.com/websockets/ws/pull/1471

and removed removed the check in https://github.com/websockets/ws/commit/297f56df79f6bf4757465fb6b59884faf5b75337

We can add it back but it would be nice to know how this can happen so we can also add a regression test.

**Comment by grimkirill** [comment]
It was happening at the high load. nodejs use near of 90% cpu usage, socket with tls and part of connections was broken by network issues. 
Maybe some of combination of:  termination + timeout + error

**Comment by grimkirill** [comment]
i think that found problem: missed remove error handler, that produced race

```
function socketOnClose() {
  ...
  this.removeListener('data', socketOnData);
  this.removeListener('error', socketOnError); // missed
  this[kWebSocket] = undefined;
```

**Comment by lpinca** [comment]
No, if you we do that and an `'error'` event emitted after the `'close'` event, it will crash the process.

**Comment by grimkirill** [comment]
Yep you are right. 
So only one way is the return of websocket check undefined, because error event can be fire after socketOnClose execution

**Comment by lpinca** [comment]
Yes I will revert https://github.com/websockets/ws/commit/297f56df79f6bf4757465fb6b59884faf5b75337.

**Comment by lpinca** [comment]
@grimkirill if you can reproduce this, can you try with Node.js 10+? I would like to see if the issue is limited to Node.js 8.

Thank you.

**Comment by lpinca** [comment]
@grimkirill any update?

**Comment by chuahcheeshian** [comment]
@lpinca I'm using Node.js 12, also having this issue as well.

**Comment by lpinca** [comment]
@chuahcheeshian same stack trace? Can you post it? Thank you.

**Comment by chuahcheeshian** [comment]
![Screen Shot 2019-07-05 at 9 52 24 AM](https://user-images.githubusercontent.com/49079535/60692955-e612ec80-9f0a-11e9-9c5f-c23db3cc1978.png)

@lpinca
On my staging servers with little to no load, this error never happened at all.
On my production servers, this error only happened randomly under high load.
With 2k concurrent WebSocket connections, this error happened at least 8 times/hour.

And when it happened, the server crashed and got restarted by Docker.
And then all the clients previously connected clients reconnected at once.
This means the server was restarted and the clients were reconnected at least 8 times/hour.
Maybe under high load, it might have a better chance to be triggered?

I had downgraded `ws` to `6.2.0` where the `if (websocket)` clause is present.
My production servers have never been restarted since then.

**Comment by lpinca** [comment]
Ok I've reverted https://github.com/websockets/ws/commit/297f56df79f6bf4757465fb6b59884faf5b75337. Will cut a new release soon.

**Comment by mortie** [comment]
I created a recording to demonstrate the issue: https://s.mort.coffee/d/vid/ws-type-error.mp4

GitHub doesn't support uploading videos, but I've uploaded a zip with the video in case I remove that video from my web server some time in the future and someone else finds this issue: 
[ws-type-error.zip](https://github.com/websockets/ws/files/3716456/ws-type-error.zip)
