### ISSUE TITLE
Error 426 after updating nginx

### ISSUE THREAD

**Issue by SiarheiGribov** [websockets/ws#1656]
Hello. After updating nginx by my hoster, connection not working: error 502 (426). Please [see conversation](https://imgur.com/a/dBNa9mj). I should to return a header "upgrade": "websocket"? How can I do that via ws?

```
var request = require('request');
const WebSocket = require('ws');

var port = process.env.PORT || 9030;

const wss = new WebSocket.Server({ port: port, verifyClient: function(info, done){
    var nickName = url.parse(info.req.url, true).query.name;
    // ...
    }
});

wss.on('connection', function(ws, req) {
    ws.on('message', function(message) {
        // ...
    });

    ws.on('close', function() {
        // ...
    });

});
```

**Comment by lpinca** [comment]
It is done by the server https://github.com/websockets/ws/blob/7.2.0/lib/websocket-server.js#L279-L284. By default you get a 426 error when you send a non upgrade request to ws server. This is why 426 is returned when your upstream server is hit via curl.

I have no idea why you get a 502 response by NGINX but it is probably because it is misconfigured and the request is not proxied correctly.

**Comment by lpinca** [comment]
By the way this is not ws issue. This issue tracker is only for bugs in the library. Please use another channel for general support questions.
