### ISSUE TITLE
ws.on does not return an event

### ISSUE THREAD

**Issue by parthnaik** [websockets/ws#1668]
Below I have simple boilerplate code as shown below:
```
const ws = new WebSocket('wss://echo.websocket.org/')

ws.on('open', () => {
    console.log('Connection opened.')
})

ws.on('message', (event) => {
    console.log(event)
    setTimeout(() => ws.close(), 1000)
})

ws.on('error', (event) => {
    console.error('An error has occurred.')
    console.error(event)
})

ws.on('close', (event) => {
    console.log('Connection closed.')
    console.log(event)
})
```

Currently, the on('message') callback will return event.data directly rather than an event. Similarly, the on('close') callback returns the error code directly rather than the event.

Is this behaviour intentional? If yes, then how can I get access to the event? Most other ws libraries will return an event rather than the data or the error code directly.

Further, since I am closing the connection manually, it should return error code 1000 but instead returns error code 1005 once the 'close' event is fired.

**Comment by lpinca** [comment]
Yes it is intentional. You can use [`websocket.addEventListener(type, listener)`](https://github.com/websockets/ws/blob/master/doc/ws.md#websocketaddeventlistenertype-listener) or [`websocket.onmessage`](https://github.com/websockets/ws/blob/master/doc/ws.md#websocketonmessage) for a browser like interface.

> Further, since I am closing the connection manually, it should return error code 1000 but instead returns error code 1005 once the 'close' event is fired.

This is also intentional. If no close code is specified, ws sends an empty close frame which results in a 1005 close code. See https://tools.ietf.org/html/rfc6455#section-7.1.5

**Comment by parthnaik** [comment]
Thanks that works!
