### ISSUE TITLE
TypeError: Cannot set property 'readyState' of undefined resurfaced?

### ISSUE THREAD

**Issue by mo22** [websockets/ws#1704]
Hi, in the current version (7.2.1) an older bug similar to https://github.com/websockets/ws/issues/1564 seems to have reappeared:

```
node_modules/ws/lib/websocket.js:837
websocket.readyState = WebSocket.CLOSING;
TypeError: Cannot set property 'readyState' of undefined
   at Socket.socketOnClose (node_modules/ws/lib/websocket.js:837:24)
   at Socket.emit (events.js:333:22)
    at Socket.EventEmitter.emit (domain.js:485:12)
```

**Comment by lpinca** [comment]
The issue was caused by invalid usage of ws by gun.js so my guess is that you are doing the same mistake. Are you using gun.js? If so see https://github.com/websockets/ws/pull/1606 and https://github.com/websockets/ws/pull/1606#issuecomment-511186215 in particular.

Please fill the issue template it's there for a reason and create a test case to reproduce the issue.

**Comment by mo22** [comment]
Yup, you're right. I do not use gun.js, but there were two WebSocket servers created for the same http server.
Maybe ws can check if there is already an instance attached to a http server?
Closing this as it is not a bug.

**Comment by lpinca** [comment]
It should, see https://github.com/websockets/ws/commit/364126620bf3fe4e6e0042d3b74ec53b5ccbbb08. I'm not sure why it is not detected in your case.
