### ISSUE TITLE
SockJS Compat

### ISSUE THREAD

**Issue by chaffeqa** [websockets/ws#1710]
### Description

I'd love to have a way to replace SockJS with this library (mainly for node client implementation)

My understanding is that sockJS has a protocol it goes through to acquire a WS URL, if we could mimic that then we could use that WS URL and run with it.

Happy to help explore that feature / documentation / example!  We have a real world use case for it

Edit: found the protocol: https://github.com/sockjs/sockjs-protocol

**Comment by lpinca** [comment]
SockJS is not a WebSocket implementation. SockJS is like Socket.IO. It's a custom protocol on top of different "transports". One of these transport is WebSocket.

You can make the SockJS client only use WebSocket as transport, but you can't replace it with a pure WebSocket library because you also have to deal with the SockJS protocol.
