### ISSUE TITLE
DoS / Crash on unmasked messages

### ISSUE THREAD

**Issue by edreal** [websockets/ws#1716]
Looks like latest ws 7.2.3 crashes if it receives message with unmasked frame.
Version 7.1.2 doesn't have this problem.

Having error handler set for socket in server fixes the problem: `ws.on('error', () => {})`
However those examples in link below doesn't have the error handler, maybe it should be added?
https://github.com/websockets/ws#simple-server

Wouldn't it be better to suppress such errors which are caused by clients if no error handler present instead of crash though?

**Comment by lpinca** [comment]
You should always add an `'error'` listener. There are different errors that can be emitted. The event is documented here https://github.com/websockets/ws/blob/master/doc/ws.md#event-error-1

Crashing when an error is emitted and there is no `'error'` listener is default Node.js behavior.

**Comment by edreal** [comment]
Hmm okay. Maybe adding empty error handler function to examples could be good idea since most people just copy those to get started so they would be secure by default.

**Comment by Luka967** [comment]
I understand that applications should be able to respond to an event like this, but I don't think that reserving the ability to crash the same application on improper client input, which the library should have already taken care of by closing, is an intuitive idea.

I myself have never paid attention to the `error` event when creating applications that use this library, and I've had a couple of projects put into production over the span of 4 years; mostly because examples haven't given any attention to it, and because my paradigm on error handling is "handle or crash". I didn't even know that `ws` didn't check the mask bit until now!

More attention should've been given to this change. Bad client input should not be able to crash an application. I don't know how many users out there have actually set a listener for the `error` event - and I will stand corrected if it turns out to not be a minority - but I consider this to be a denial of service exploit. Libraries should be made with a fool-proof mindset, especially in fields highly sensitive to consistency like networking.

**Comment by lpinca** [comment]
Invalid frames have always emitted an error

- An error is emitted if the RSV2 or the RSV3 bit are set
- An error is emitted if the opcode is invalid
- An error is emitted if the max payload is exceeded

etc.

This is nothing new. In Node.js you have to add `'error'` listeners.

**Comment by Luka967** [comment]
Given node.js' paradigm on errors and events, it sounds reasonable enough now when I think of it again. I suppose that at least giving more attention to the `error` event should be appropriate - let others know that it can be emitted in case the other endpoint sends an unacceptable frame which can be ignored, rather than just "for errors".
