### ISSUE TITLE
WS_ERR_EXPECTED_MASK

### ISSUE THREAD

**Issue by dailytabs** [websockets/ws#1971]
### 

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Receiving `WS_ERR_EXPECTED_MASK` on my WS server after I send a `ws.ping(cb)` on a client ws.

Does this mean the remote WS is sending their pong incorrectly, according to the spec? (I.E. They are responding as if they are a server, and not a client?)

### ws version

7.5.5

### Node.js Version

FROM node:14 (docker)

### System

 System:
    OS: Linux 5.10 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 9.83 GB / 24.85 GB
    Container: Yes
    Shell: 4.4.12 - /bin/bash

### Expected result

Pong to be received properly. (Sorry, this is more of a question.)

### Actual result

```WebSocket encountered an error. {
error: RangeError: Invalid WebSocket frame: MASK must be set
    at Receiver.getInfo (/opt/tdp-ws-service/node_modules/ws/lib/receiver.js:284:16)
    at Receiver.startLoop (/opt/tdp-ws-service/node_modules/ws/lib/receiver.js:131:22)
    at Receiver._write (/opt/tdp-ws-service/node_modules/ws/lib/receiver.js:78:10)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Receiver.Writable.write (internal/streams/writable.js:303:10)
    at Socket.socketOnData (/opt/tdp-ws-service/node_modules/ws/lib/websocket.js:1077:35)
    at Socket.emit (events.js:375:28)
    at Socket.emit (domain.js:470:12)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9) {
  code: 'WS_ERR_EXPECTED_MASK',
  [Symbol(status-code)]: 1002
},

### Attachments

_No response_

**Comment by lpinca** [comment]
> Does this mean the remote WS is sending their pong incorrectly, according to the spec? (I.E. They are responding as if they are a server, and not a client?)

Yes, all frames coming from a client must be masked.

**Comment by lpinca** [comment]
I'm closing this as answered. Discussion can continue if needed.

**Comment by dailytabs** [comment]
Yes, thank you. I discussed with my team and completely forgot to come back here. Tysm for the verification. It seems our old server had a custom pong implementation to work around this issue. I believe we are going to fix it on the client side (properly) this time around.

**Comment by derekrprice** [comment]
I was just looking at the client here, though.  It is interesting to note that the pong response contains no data, so there is nothing TO mask.  Technically, the mask field is still required by my reading of the spec, but there is nothing to apply the mask to because the client is responding with a 0 byte packet.

So, technically, the mask bytes are required by the spec even for a 0 length packet but, since they are unused, this seems to be a special case where the server could harmlessly ignore the missing mask and save the 4 bytes on the wire.

**Comment by lpinca** [comment]
Yes, even empty frames must be masked. The server should still read the 4 bytes of the mask even if they are not used to properly parse the next frame.

**Comment by lpinca** [comment]
We could not store the mask if the payload length is zero

https://github.com/websockets/ws/blob/8.2.3/lib/receiver.js#L399

but it would only save 4 bytes until the next frame is parsed.

**Comment by derekrprice** [comment]
We are only interested because we have a client which is masking everything except pong responses.  We do control the client code and can fix it there, but it's firmware on an IoT device, so firmware updates can take some time to roll out.  Since these devices are usually connecting via cell, saving 4 bytes every 4 seconds (our ping interval) might add up, but it would still be a small percentage of the overall data used on the connection.

Whichever way you decide to go with it, I don't think you want to choose to skip consumption based on the payload length, but simply make an exception for the [mask requirement](https://github.com/websockets/ws/blob/cfd99b6309d59da5c35c4087520b480ec060cbd9/lib/receiver.js#L287), using `if (!this._masked && this._payloadLength > 0) {` there instead of simply checking the mask bit before throwing the error like it does now.

**Comment by lpinca** [comment]
Accepting frames with the mask bit off on the server is a spec violation.

**Comment by derekrprice** [comment]
Yes.  That's what I was trying to say above.  It's technically a spec violation, but since there is no data TO mask, ignoring the violation in the very specific case where payload length is 0 should be harmless.

Regardless, I can't blame you for not wanting to fix it either.  We'll get the client fixed eventually.
