### ISSUE TITLE
doc: Missing information about v7 support

### ISSUE THREAD

**Issue by Nautigsam** [websockets/ws#2072]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

I see you occasionally backport some commits to the v7 branch. Do you plan to provide long-term support for 7.x versions? In any case, it would be great to have this specified somewhere in the README or in the docs.

**Comment by lpinca** [comment]
There is no documentation because there is no plan. The only officially supported release line is the latest, 8.x. Security fixes have been backported to the 7.x release line because it is not easy to upgrade when `ws` is used as an indirect dependency. However, `ws@8.0.0`  was released more than a year ago, so probably no more fixes will be backported.

**Comment by Nautigsam** [comment]
All right. I'm closing this one, then. Thank you for your work on this project.
