### ISSUE TITLE
this.terminate(); 在哪写的 没看懂   应该是 client.terminate() 吧

### ISSUE THREAD

**Issue by Blizzard-liu** [websockets/ws#2144]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

![image](https://github.com/websockets/ws/assets/20244432/136ac013-226e-4c8e-88ca-47b0e3a3a2e7)

**Comment by lpinca** [comment]
I don't understand. Can you please describe the issue?

**Comment by lpinca** [comment]
Issue title is translated like this by Google Translate

"this.terminate(); Where is it written? I don’t understand. It should be client.terminate()"

The answer is that `this` in the `heartbeat` function is `client` because it is used in `client.on('ping', heartbeat)` and `this` is set to reference the `EventEmitter` when the event is emitted. See https://nodejs.org/api/events.html#passing-arguments-and-this-to-listeners.

**Comment by lpinca** [comment]
I'm closing this as answered.

**Comment by Blizzard-liu** [comment]
ok  牛逼  我傻逼了

**Comment by xbsheng** [comment]
> ok 牛逼 我傻逼了

牛逼
