### ISSUE TITLE
Remove node-gyp from "install"

### ISSUE THREAD

**Issue by adam-lynch** [websockets/ws#320]
Is there any chance you could please somehow remove the calling of `node-gyp` on the user's side? It's a real pain for Windows users :/

**Comment by polkovnikov-ph** [comment]
Why this issue has been closed? `ws` build is not working at Windows, which is still a target for Node.js.

`node-gyp` has serious Unicode problems (someone forgot it's 2015) and requires Python to build Javascript libraries (this even sounds quite funny), so it cannot be a thing someone needs to build plugins at all. It's a piece of wide-used non-supported crap.

Long path problems at Windows are easily solved by the `\\?\` prefix. A lot of non-Windows guys tell Windows guys to go get better at their Windows magic, because it's Windows that is a source of the pain, but not those non-Windows guys. Sorry, but that's not true. It's not the Windows that `Cannot open include file: 'v8.h'`. It's a piece of bad third-party software. And no Windows magic can help me at this.

For the sake of Node.js community, reopen this. Please.

**Comment by 3rd-Eden** [comment]
@polkovnikov-ph This issue was closed as the binary addons are moved to the `optionalDependencies` part of the `package.json` so if the installation or compilation of these files fail, the installation should still complete. 

If this is not the case, you should raise an issue in the `npm` library as they handle the optionalDependency installation.

**Comment by bgSosh** [comment]
@3rd-Eden Could you tell me what the binary addons were, and what the performance implications on not using them might be please?  Thanks.

**Comment by 3rd-Eden** [comment]
The binary components are also in the organization, they are bufferutil and utf-8 validate. Bufferutil improves the performance of buffer based operations and creating websocket masks while utf8-validate adds missing utf-8 validation so the library is confirm the RFC specification.

**Comment by bgSosh** [comment]
Thanks.  So in situations that don't use websocket masks, do you know (very roughly) what kind of a performance gain the binary bufferutil would give over the fallback?
