### ISSUE TITLE
how do i include ws on the client side?

### ISSUE THREAD

**Issue by r3wt** [websockets/ws#423]
i have a massive `php` application that i would like to move from pusher to `node.js` using the `ws` library i've already fumbled around enough to get the server working and have pushed the code the app servers and they are running. now i need to update the client code, and **i'm at a loss for how i might require the ws library in my html views of the php app**? could you please instruct?

**Comment by matanster** [comment]
Why then does the example code at https://einaros.github.io/ws/ require the library on the client side?
Any issues using the built-in browser websocket implementations?

**Comment by jakeknerr** [comment]
@matanster I think when they are using a require on the client-side they are referring to using the library in a non-browser client, like another node server. Server client to server server type of thing.

**Comment by tsm91** [comment]
Not only the readme shows the clientside usage, but also the api docs shows methods that are not implemented by the default websockets. For example https://github.com/websockets/ws/blob/master/doc/ws.md#class-websocket the `ping` method.

And yes, you will get a runtime error if u try to require this on the clientside. 

So ill have to implement the ping method. @matanster have u wrote a 3rd party plugin?

**Comment by matanster** [comment]
@tsm91 a plugin? no

**Comment by santi6291** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_client_applications

**Comment by titansoftime** [comment]
Yea, I found the docs to be confusing. It sure makes it look like you would use node on the browser client...

Why not provide a standard use case scenario (browser + server) as opposed to having multiple node servers communicating?

**Comment by Dvisacker** [comment]
Quick question about this, would it technically be possible to use this library or at least most of it's functionality on the browser ? 

I'm having trouble with the native websocket API because it's functionality is quite limited. For example, i didn't not find the way to proxy requests with the native websocket API ( new WebSocket('/proxy/') fails because all urls are required to be ws:// or wss:// ). It seems like the ws libraries just from quick testing and from looking at the API, but unfortunately, it doesn't seem to be working on the browser.

**Comment by tsingson** [comment]
try this:  https://github.com/heineiuo/isomorphic-ws
