### ISSUE TITLE
Socket becomes unwritable before 'close' event is emitted

### ISSUE THREAD

**Issue by jondubois** [websockets/ws#464]
This can be problematic, because if you have code like this:

``` js
var emitInterval = setInterval(function () {
  socket.send('this is a string');
}, 100);

socket.on('close', function () {
  clearInterval(emitInterval);
});
```

You will often get 'Socket Error: not opened' when you disconnect the socket/refresh the browser. It seems that the socket becomes unwritable before the 'close' event is emitted (readyState set to CLOSING). It would be nice if there was a way to detect when the socket stops being open.

**Comment by jondubois** [comment]
I looked into the issue a bit deeper...
At the point where it throws the 'not opened' error, the readyState is CLOSING. So the error makes sense I guess.

In that case, it would be nice to have a 'closing' event in addition to the 'close' event in order to support the use case mentioned above.

**Comment by jondubois** [comment]
@3rd-Eden If I added a 'closing' event would you accept the PR?
Would that be the right approach?

I feel that being able to detect when a connection is 'not open' may be more useful than detecting when it is strictly CLOSED.

**Comment by nkzawa** [comment]
I'm not against `closing` event, but I think this problem happens on browser WebSocket client as well.
And you can catch this error if pass a callback to `send` like the following.

```js
socket.send('foo', function(err) {
  if (err) console.log('an error happened');
});
```

**Comment by jondubois** [comment]
@nkzawa Good point about clients.

When reading the W3C recommendation for the WebSocket API (http://www.w3.org/TR/websockets/), it doesn't mention a 'closing' event so it would not be W3C compliant :(((

It feels like the WebSocket API standard is lagging behind... It would be nice to have an event triggered for every state change possible.

**Comment by 3rd-Eden** [comment]
Well, the problem here is that you made the assumption that you can just always bluntly write to a websocket connection. This is not the case on the server or browser. Normally you would wrap your write/send api with a readyState check to ensure that the connection open as the browser would also throw an Error if you're writing to a closed websocket.

I don't know the exact flow of events in the browser but I feel that we should follow it as close as possible to prevent people from writing the same code twice (on server and client)
