### ISSUE TITLE
Send message to everyone except sender

### ISSUE THREAD

**Issue by cra0kalo** [websockets/ws#465]
Hey guys just started using ws how would I only send or broadcast a message from a client to all other clients except the sender. Theres very little example code I couldn't find anything.

		//when the client sends a message  
        ws.on("message", function(message) {
                console.log("Received: %s", message);
                server.broadcast(message);

my broadcast method has a for each loop currently

        server.clients.forEach(function(client) {		
                client.send(data);
        }

**Comment by glennschler** [comment]
You may want to look at Socket.io which enhances WebSockets with an
implementation which allows for broadcasting.

**Comment by glennschler** [comment]
You seem to be doing it correctly. Though, Socket.io already enhances this
WebSocket implementation with additional support for broadcasting.

**Comment by 3rd-Eden** [comment]
@glennschler are you seriously advising socket.io because there a single if statement missing in the `forEach` code? I don't even.. 

```js
ws.on("message", function(message) {
  server.clients.forEach(function(client) {       
    if (client !== ws) client.send(data);
  });
});
```

@cra0kalo The only thing that your code was missing was a simple `if` statement to check if the client that you received from the forEach was not the same as the `ws` client that received the message.

**Comment by glennschler** [comment]
@3rd-Eden no, I thought that this project is a pure RFC-6455 implementation of Websocket. So if a user implements broadcasting themselves, then this project is the best option. If someone is asking if broadcasting is an implemented feature of this API, then I think that is outside of the spec and is one of the reasons why engine.io/socket.io exists. I realize now this issue was not directly asking to modify the API, so please excuse my suggestion.

**Comment by cra0kalo** [comment]
Thankyou 3rd-Eden got it working sir
