### ISSUE TITLE
Is the order of messages guaranteed? 

### ISSUE THREAD

**Issue by bitliner** [websockets/ws#542]
I did not find it explicitly in the RFC.

Is the order of operations guaranteed?

In other words

if clients do

```
// first op - client 1
.send(1)

// second op - client 2
.send(2)
``` 

then the receiver always receives

```
1
2
```

and never 

```
2
1
```

Could you confirm it?

**Comment by jondubois** [comment]
TCP itself offers in-order, exactly-once delivery guarantee so yes WS also does by extension. HTTP doesn't provide this guarantee because HTTP requests may be spread over multiple TCP connections (and this negates the guarantee). Since a WebSocket uses a single TCP connection, this guarantee is maintained.

**Comment by devinivy** [comment]
@jondubois :+1: nicely said– thanks.

**Comment by jondubois** [comment]
@patrickelectric I believe the issue is specific to that implementation itself awaiting on blob.arrayBuffer() which can take longer to resolve for some messages than others. So the messages arrive in-order but they finish processing in a potentially different order. It's the exact reason why SocketCluster focuses on for-await-of loops. So it shouldn't be an issue with SC if you use it as documented.
