### ISSUE TITLE
Time for new NPM version?

### ISSUE THREAD

**Issue by mkamioner** [websockets/ws#547]
When are you planning on updating the NPM module?

Thanks :-)
Mo

**Comment by 3rd-Eden** [comment]
When IO.js 3.0 is supported.

**Comment by mkamioner** [comment]
Is there a timeline on that?

If it is not going to be for a while, maybe it makes more sense to make a new version of what exists now?

**Comment by 3rd-Eden** [comment]
Just added iojs support a few hours ago, so i'll probably kick out a new version today or tmorrow.

**Comment by TuckerWhitehouse** [comment]
:+1:

**Comment by sanemat** [comment]
:+1:

**Comment by ide** [comment]
@3rd-Eden do you feel that io.js 3.x support is ready to publish? People would like to get it from npm soon (#555, #549).

**Comment by 3rd-Eden** [comment]
@ide theres still a small issue with the binary addons not compiling on certain environments.

**Comment by ide** [comment]
@3rd-Eden does the compiler issue affect all versions of Node/iojs or just io.js 3.x? I noticed the Travis tests failed with io.js 3.0 but passed with 1.x and 2.x.

If the problem is only with 3.x, would you be open to publishing 0.7.3 because it is still compatible with all the node/iojs versions that work with 0.7.2?

**Comment by 3rd-Eden** [comment]
0.8 was released a while ago.

**Comment by mkamioner** [comment]
:+1: Thanks @3rd-Eden
