### ISSUE TITLE
Project name

### ISSUE THREAD

**Issue by dit-j** [websockets/ws#592]
Hi 
since it is very hard, to find some information about ws and only ws via Search Engine, it would be nice to rename the project using some nice unique name. (like Socket.IO did)

Sorry for this non Programming-Issue, but this is very important. ws is not really powerful name for so powerful library.

**Comment by 3rd-Eden** [comment]
At this point we can't really change the name because there are already so many projects depending on it and articles written about it especially if we take the poor support module renaming in npm which is effectively creating a new package and hoping that it will be picked up.

So yeah, it's kinda hard name to find but not much we can do about it -- unless you have suggestions.
