### ISSUE TITLE
Cannot find module "fs"

### ISSUE THREAD

**Issue by JoeDawson** [websockets/ws#662]
Hello,

Firstly, I'm sorry if this isn't an issue related to the ws library - but I had to start somewhere.

I'm currently working on a project with Vue.js - my current code looks like this.

```
import Vue from 'vue';

new Vue({

	ready: function() {

		this.connect();

	},

	data: function() {
		return {
			socket: null
		}
	},

	methods: {

		/**
		 * Connect to the Pushover WebSocket in order to
		 * retrieve push notifications.
		 * 
		 * @return mixed
		 */
		connect: function() {

			var WebSocket = require('ws');

			this.socket = new WebSocket('wss://client.pushover.net/push:443');

			this.socket.on('open', function() {
				this.socket.send('login:' + localStorage.getItem('device_id'));
			});

			this.socket.on('message', function(data) {
				console.log(data);

				alert('got a message');
			});

		}

	},

});
```

When the `connect` method is called, I get the following error in my console.

> Uncaught Error: Cannot find module "fs"

Do you have any idea why I might be receiving this? I know everything but the code within my `connect` method is ok as I've tested this.

I hope you can help!

**Comment by 3rd-Eden** [comment]
I honestly don't know why you are getting this error but it's in no way related to `ws`. The `fs` is a core module of `node` so if that is missing there is something seriously wrong with either your installation or how you are using the code.

**Comment by JoeDawson** [comment]
Only happens when I use this library though - hence the reason for the issue. I'll continue to investigate elsewhere :)

**Comment by hrmoller** [comment]
@JoeDawson Experiencing the same issue here, have you the found the reason?

**Comment by JoeDawson** [comment]
@hrmoller unfortunately ended up abandoning the library and using navtive WebSockets in the end. But of a shame, but I think it was related to my webpack config somehow if that helps point you in the right direction?

**Comment by zalmoxisus** [comment]
Actually the issue is deeper. Before `Uncaught Error: Cannot find module "fs"` there's another one that caused this one:
```
Actually the issue is deeper. Before `Uncaught Error: Cannot find module "fs"` there's another one that caused this one:
```
WARNING in /.../~/bindings/bindings.js
Critical dependencies:
76:22-40 the request of a dependency is an expression
76:43-53 the request of a dependency is an expression
 @ /.../~/bindings/bindings.js 76:22-40 76:43-53

WARNING in /.../~/bindings/package.json
Module parse failed: /.../node_modules/bindings/package.json Line 2: Unexpected token :
You may need an appropriate loader to handle this file type.
| {
|   "_args": [
|     [
|       "bindings@1.2.x",
 @ /.../~/bindings ^\.\/.*$

WARNING in /.../~/bindings/README.md
Module parse failed: /.../node_modules/bindings/README.md Line 2: Unexpected token ===
You may need an appropriate loader to handle this file type.
| node-bindings
| =============
| ### Helper module for loading your native module's .node file
| 
 @ /.../~/bindings ^\.\/.*$

ERROR in /.../~/ws/lib/WebSocketServer.js
Module not found: Error: Cannot resolve module 'tls' in /.../node_modules/ws/lib
 @ /.../~/ws/lib/WebSocketServer.js 15:10-24

ERROR in /.../~/options/lib/options.js
Module not found: Error: Cannot resolve module 'fs' in /.../node_modules/options/lib
 @ /.../~/options/lib/options.js 6:9-22
```

So the issue is related to the fact that Webpack cannot require `tls`, which is nodejs specific:
```
ERROR in /.../~/ws/lib/WebSocketServer.js
Module not found: Error: Cannot resolve module 'tls' in /.../node_modules/ws/lib
 @ /.../~/ws/lib/WebSocketServer.js 15:10-24
```

**Comment by zalmoxisus** [comment]
The solution is to use `const ws = __non_webpack_require__('ws');` there, so it would be imported like nodejs module.

**Comment by zalmoxisus** [comment]
The problem doesn't appear in `0.8.x` as there's a fallback for browser in package.json:
```
"browser": "./lib/browser.js"
```

**Comment by ausrasul** [comment]
Incompatibility with webpack should be in README.
That would have saved me half a day before going to native ws.

**Comment by xxd3vin** [comment]
Similar error is https://github.com/webpack/react-starter/issues/3#issuecomment-53395089

When developing isomorphic javascript app, the packages we `require`ed should have `browser` field in `package.json` to tell, for example webpack, to exclude server-side module. I think `ws` would be nice to add this to `package.json`:

```diff
     "tinycolor": "0.0.x",
     "utf-8-validate": "1.2.x"
   },
+  "browser": {
+    "fs": false,
+    "tls": false
+  },
   "gypfile": true
 }
```

Otherwise, we could add this to `webpack.config.js`

```diff
         loaders: ['style', 'raw']
       }
     ]
+  },
+  node: {
+    fs: 'empty',
+    tls: 'empty'
   }
 };
```

**Comment by zEh-** [comment]
**target: 'node'** in webpack.config.js : )

**Comment by Vastness** [comment]
I'm new to ws,and I just got the same problem today.
Then I follow the solution as @xxd3vin says,however, I got an new problem as 
[http://stackoverflow.com/questions/29829597/i-get-a-status-200-when-connecting-to-the-websocket-but-it-is-an-error#](url) mentioned.
Thus, I realized there is something seriously wrong with how we are using the code.

> In the browser, you are using the native WebSocket class and not SockJS !

So, we should just remove `var WebSocket = require('ws');` and change the url to `var ws = new WebSocket(yourhost+'/websocket')` in the client side js. Finally, solve the problem perfectly.
