### ISSUE TITLE
What's the purpose of the default close code?

### ISSUE THREAD

**Issue by tejasmanohar** [websockets/ws#715]
What's the purpose of [this](https://github.com/websockets/ws/blob/master/lib/Sender.js#L50)-
```js
code = code || 1000;
```
if you check
```js
if (typeof code !== 'undefined') {
  if (typeof code !== 'number' ||
    !ErrorCodes.isValidErrorCode(code)) throw new Error('first argument must be a valid error code number');
}
```
right before it?

**Comment by LongLiveCHIEF** [comment]
If `close` is called with anything other than `close()` or `close(<Number>)`, then the preceding code will check to see if there's a custom non-numerical closure code registered.  

The line `code = code || 1000` is then a way to set the `close` functions default error code value to `1000`, so that if you call `close()`, it is essentially the same thing as calling `close(1000)`.

**Comment by goktugyil** [comment]
You can also use codes between 4000-4999

https://tools.ietf.org/html/rfc6455
