### ISSUE TITLE
Why are bufferutils and utf-8-validate dev-dependencies?

### ISSUE THREAD

**Issue by CxRes** [websockets/ws#719]
I am sorry if this sounds like a support request but it causes warnings when I try to bundle my app with ws as a dependency. Webpack sees the require statements and is then upset that it cannot find the two libs because obviously they are not installed. 

I know there are fallbacks for the two concerned libs but wouldn't it be better to define them as dependencies and let npm install them and something like webpack the being able to find and bundle them?

**Comment by 3rd-Eden** [comment]
They are devDependencies because they are optional binary dependencies. Adding them as optionalDependencies didn't work because npm still cuased the installation to fail when it failed to compile. 

You should completely ignore this library in your webpack build in order to make it work. There's no client side logic here that can be bundled anyways.
